# Generated by Django 2.2.6 on 2019-11-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
